"""Browser tests for the SPA imports page (#136).

Drives the built SPA against a real ``potluck serve`` with synthetic archives
(generated by ``potluck.testing`` — never real exports): the upload flow, the
server-path flow over a two-part Takeout set, failed imports with actionable
errors, and the busy/too-large notices.

The concurrent-start (409) and oversized-upload (413) notices are exercised
via intercepted responses carrying the API's exact error envelope: gating a
real concurrent import on timing is flaky because synthetic fixtures import
in milliseconds.

Runs only with ``-m browser`` (excluded by default); requires ``web/dist``
and Playwright chromium.
"""

import shutil
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
from playwright.sync_api import Page, Route, expect

from potluck.core.config import Settings
from potluck.ingest.engine import run_import
from potluck.models.drafts import EmailDraft
from potluck.services.context import create_context
from potluck.services.imports import import_path
from potluck.testing.keep import write_keep_takeout
from potluck.testing.mbox import synthetic_email_drafts, write_gmail_takeout
from tests.e2e.conftest import api_get, serve_app

pytestmark = pytest.mark.browser

SEED = 7

BUSY_BODY = (
    '{"error":{"code":"import_in_progress","message":'
    "\"an import of '/exports/big-takeout-001.zip' is already running; "
    'only one import runs at a time"}}'
)
TOO_LARGE_BODY = (
    '{"error":{"code":"upload_too_large","message":'
    "\"upload 'takeout-synth-001.zip' exceeds the configured limit of "
    '10737418240 bytes (settings: max_upload_bytes)"}}'
)


@pytest.fixture
def server_url(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Iterator[str]:
    """A fresh empty database per test; XDG_DATA_HOME pinned into tmp so the
    managed uploads directory never touches the developer's real data dir."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    with serve_app(tmp_path / "potluck.db", tmp_path / "config") as url:
        yield url


def api_imports(url: str) -> dict[str, Any]:
    """Ground-truth import history straight from the API."""
    return api_get(url, "/api/imports")


# ---------------------------------------------------------------------------
# Upload flow: fixture zip -> progress -> completed history row
# ---------------------------------------------------------------------------


def test_upload_zip_progress_then_history_row(server_url: str, tmp_path: Path, page: Page) -> None:
    archive = write_keep_takeout(tmp_path / "fixture", 12, seed=SEED, fmt="zip")

    page.goto(f"{server_url}/imports")
    expect(page.get_by_test_id("history-empty")).to_be_visible()

    page.get_by_test_id("upload-input").set_input_files(archive)

    # The 202 task snapshot seeds the UI the moment the POST resolves, so the
    # current-import card shows deterministically (for at least one poll
    # cycle) even though a 12-note import finishes server-side in ms.
    current = page.get_by_test_id("current-import")
    expect(current).to_be_visible()
    expect(current).to_contain_text("takeout-synth-001.zip")

    # The run lands in history as completed, with the same row shape as path
    # mode (the upload was stored under the managed uploads dir).
    row = page.get_by_test_id("history-row").first
    expect(row).to_have_attribute("data-status", "completed", timeout=15_000)
    expect(row).to_have_attribute("data-source", "google_keep")
    expect(row).to_contain_text("takeout-synth-001.zip")

    # Counts match the ledger row exactly (API = ground truth).
    truth = api_imports(server_url)["runs"][0]
    assert truth["items_done"] > 0
    expect(row.get_by_test_id("history-items")).to_contain_text(str(truth["items_done"]))
    expect(row.get_by_test_id("history-items")).to_contain_text(f"{truth['items_new']} new")

    # The operation settled: the current-import card goes away, polling stops.
    expect(current).to_have_count(0)


# ---------------------------------------------------------------------------
# Path mode: a TWO-PART Takeout set (Keep in part 1, Mail in part 2)
# ---------------------------------------------------------------------------


def test_path_mode_two_part_takeout_set(server_url: str, tmp_path: Path, page: Page) -> None:
    keep_zip = write_keep_takeout(tmp_path / "keep", 10, seed=SEED, fmt="zip")
    mail_zip = write_gmail_takeout(tmp_path / "mail", 15, seed=SEED, fmt="zip")
    set_dir = tmp_path / "takeout-set"
    set_dir.mkdir()
    part1 = set_dir / "takeout-e2e-001.zip"
    shutil.copy(keep_zip, part1)
    shutil.copy(mail_zip, set_dir / "takeout-e2e-002.zip")

    page.goto(f"{server_url}/imports")
    page.get_by_test_id("path-input").fill(str(part1))
    page.get_by_test_id("path-import-button").click()
    expect(page.get_by_test_id("current-import")).to_be_visible()

    # Pointing at ONE part imported the whole set: one operation, one ledger
    # row per detected source, both completed.
    rows = page.get_by_test_id("history-row")
    expect(rows).to_have_count(2, timeout=15_000)
    gmail_row = page.locator('[data-testid="history-row"][data-source="gmail"]')
    keep_row = page.locator('[data-testid="history-row"][data-source="google_keep"]')
    expect(gmail_row).to_have_attribute("data-status", "completed", timeout=15_000)
    expect(keep_row).to_have_attribute("data-status", "completed")
    # Both rows record the part the user pointed at.
    expect(gmail_row).to_contain_text("takeout-e2e-001.zip")
    expect(keep_row).to_contain_text("takeout-e2e-001.zip")

    truth = {run["source"]: run for run in api_imports(server_url)["runs"]}
    assert truth["gmail"]["items_done"] > 0 and truth["google_keep"]["items_done"] > 0
    expect(gmail_row.get_by_test_id("history-items")).to_contain_text(
        str(truth["gmail"]["items_done"])
    )
    expect(keep_row.get_by_test_id("history-items")).to_contain_text(
        str(truth["google_keep"]["items_done"])
    )


# ---------------------------------------------------------------------------
# Failed imports: actionable errors
# ---------------------------------------------------------------------------


def test_failed_import_shows_actionable_error(server_url: str, tmp_path: Path, page: Page) -> None:
    page.goto(f"{server_url}/imports")

    # A nonexistent path fails fast (400) -> inline notice, no background task.
    missing = tmp_path / "missing.zip"
    page.get_by_test_id("path-input").fill(str(missing))
    page.get_by_test_id("path-import-button").click()
    notice = page.get_by_test_id("start-error")
    expect(notice).to_be_visible()
    expect(notice).to_contain_text("no such file or directory")
    expect(page.get_by_test_id("task-failed")).to_have_count(0)

    # A corrupt archive passes the existence check, then fails during the
    # background detection phase — before any ledger row exists, so the
    # failure surfaces on the task card with the translated error.
    corrupt = tmp_path / "corrupt.zip"
    corrupt.write_bytes(b"PK\x03\x04" + b"\x00" * 64)
    page.get_by_test_id("path-input").fill(str(corrupt))
    page.get_by_test_id("path-import-button").click()
    failed = page.get_by_test_id("task-failed")
    expect(failed).to_be_visible(timeout=10_000)
    expect(failed).to_contain_text("corrupt.zip")
    expect(failed.get_by_test_id("task-error")).to_contain_text("corrupt or unreadable archive")

    # Actionable: the retry affordance refills the path input for a fix.
    page.get_by_test_id("path-input").fill("")
    failed.get_by_test_id("task-retry").click()
    expect(page.get_by_test_id("path-input")).to_have_value(str(corrupt))

    # And the notice is dismissable without losing the page.
    failed.get_by_role("button", name="Dismiss").click()
    expect(failed).to_have_count(0)


def test_failed_history_row_error_expands_and_retries(
    tmp_path: Path, page: Page, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Seed a database with one completed run and one genuinely failed run —
    # through the real engine failure path (mid-parse exception marks the
    # ledger row failed with the error text, then re-raises).
    db_path = tmp_path / "potluck.db"
    settings = Settings(
        db_path=db_path,
        extract_attachments=False,
        attachments_dir=tmp_path / "attachments",
        uploads_dir=tmp_path / "uploads",
    )
    long_error = (
        "mbox member truncated at message 4: unexpected EOF while decoding a "
        "base64 attachment body — the archive appears incomplete; re-export "
        "this data from Google Takeout and import the fresh file instead"
    )
    broken_path = tmp_path / "broken-takeout-001.zip"

    def failing_drafts() -> Iterator[EmailDraft]:
        yield from synthetic_email_drafts(3, seed=SEED)
        raise RuntimeError(long_error)

    ctx = create_context(settings)
    try:
        import_path(ctx, write_keep_takeout(tmp_path / "keep", 5, seed=SEED, fmt="zip"))
        with pytest.raises(RuntimeError):
            run_import(
                ctx.db,
                source_name="gmail",
                parser_version=3,
                drafts=failing_drafts(),
                path=str(broken_path),
                file_hash=None,
            )
    finally:
        ctx.db.close()

    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    with serve_app(db_path, tmp_path / "config") as url:
        page.goto(f"{url}/imports")
        failed_row = page.locator('[data-testid="history-row"][data-status="failed"]')
        expect(failed_row).to_be_visible()
        expect(failed_row).to_have_attribute("data-source", "gmail")
        # Newest first: the failed gmail run precedes the completed keep run.
        expect(page.get_by_test_id("history-row").first).to_have_attribute("data-status", "failed")
        expect(page.get_by_test_id("history-row").nth(1)).to_have_attribute(
            "data-status", "completed"
        )

        # The error renders clamped, expands on demand, and offers a retry
        # that refills the path input with the failed archive's path.
        error = page.get_by_test_id("history-error")
        expect(error).to_contain_text("truncated at message 4")
        expect(error).to_have_attribute("data-expanded", "false")
        error.get_by_role("button", name="Show more").click()
        expect(error).to_have_attribute("data-expanded", "true")
        expect(error.get_by_role("button", name="Show less")).to_be_visible()
        error.get_by_test_id("history-retry").click()
        expect(page.get_by_test_id("path-input")).to_have_value(str(broken_path))


# ---------------------------------------------------------------------------
# Busy (409) and too-large (413) notices — intercepted envelopes
# ---------------------------------------------------------------------------


def test_busy_and_too_large_notices(server_url: str, tmp_path: Path, page: Page) -> None:
    page.goto(f"{server_url}/imports")

    # 409 import_in_progress -> a calm inline notice, not a crash.
    def busy_on_post(route: Route) -> None:
        if route.request.method == "POST":
            route.fulfill(status=409, content_type="application/json", body=BUSY_BODY)
        else:
            route.continue_()

    page.route("**/api/imports", busy_on_post)
    page.get_by_test_id("path-input").fill("/exports/other.zip")
    page.get_by_test_id("path-import-button").click()
    busy = page.get_by_test_id("start-busy")
    expect(busy).to_be_visible()
    expect(busy).to_contain_text("already running")
    page.unroute("**/api/imports")
    busy.get_by_role("button", name="Dismiss").click()
    expect(busy).to_have_count(0)

    # 413 upload_too_large -> a clear size message naming the limit.
    page.route(
        "**/api/imports/upload",
        lambda route: route.fulfill(
            status=413, content_type="application/json", body=TOO_LARGE_BODY
        ),
    )
    archive = write_keep_takeout(tmp_path / "fixture", 3, seed=SEED, fmt="zip")
    page.get_by_test_id("upload-input").set_input_files(archive)
    error = page.get_by_test_id("start-error")
    expect(error).to_be_visible()
    expect(error).to_contain_text("exceeds the configured limit")
