"""Knowledge notes model for Potluck-native notes.

KnowledgeNotes are pieces of useful information stored in Potluck itself,
not imported from external sources like Google Keep or Obsidian.

Think of it as an LLM memory function - capturing insights, facts, and
relationships that don't have a hard tie to a source but can benefit
other models (e.g., "I went to school with Jack", "Alice's favorite
restaurant is Pizzeria Uno").

Notes can be:
- Added directly by users
- Created by LLMs during conversations
- Generated by automated analysis of imported data
"""

from typing import ClassVar

from pgvector.sqlalchemy import Vector
from sqlalchemy import Column
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlmodel import Field

from potluck.core.constants import MULTIMODAL_EMBEDDING_DIM, TEXT_EMBEDDING_DIM
from potluck.models.base import SimpleEntity


class KnowledgeNote(SimpleEntity, table=True):
    """A Potluck-native knowledge note with text and embedding.

    Used for storing insights, facts, and relationships that enrich
    the knowledge graph without being tied to a specific import source.

    Inherits id, created_at, updated_at from SimpleEntity.
    """

    __tablename__ = "knowledge_notes"

    # Search configuration - content auto-discovered
    __searchable__: ClassVar[bool] = True
    __search_exclude_fields__: ClassVar[set[str]] = set()
    __search_priority_fields__: ClassVar[set[str]] = set()
    __search_date_fields__: ClassVar[set[str]] = {"created_at"}

    def to_text_repr(self) -> str:
        """Return text representation with ID for LLM context."""
        content_preview = (self.content or "")[:100]
        if len(self.content or "") > 100:
            content_preview += "..."
        creator = self.created_by or "unknown"
        return f"Note (id: {self.id}): {content_preview} | by: {creator}"

    # Note content
    content: str = Field(
        description="The note text content",
    )
    content_hash: str | None = Field(
        default=None,
        index=True,
        description="SHA256 hash of content for deduplication",
    )

    # Embeddings for semantic search
    embedding: list[float] | None = Field(
        default=None,
        sa_column=Column(Vector(TEXT_EMBEDDING_DIM)),
        description="Text embedding for text-to-text semantic search",
    )
    multimodal_embedding: list[float] | None = Field(
        default=None,
        sa_column=Column(Vector(MULTIMODAL_EMBEDDING_DIM)),
        description="Multimodal embedding for text-to-image cross-modal search",
    )

    # Full-text search vector (auto-populated by database trigger)
    search_vector: str | None = Field(
        default=None,
        sa_column=Column(TSVECTOR),
        description="FTS vector for keyword search (auto-populated by trigger)",
    )

    # Creation context
    created_by: str | None = Field(
        default=None,
        description="What created this note (e.g., 'user', 'claude', 'auto-linker')",
    )

    # Optional linked entities (JSON-encoded UUIDs with entity types)
    linked_entities: str | None = Field(
        default=None,
        description="JSON-encoded list of {entity_type, entity_id} for related entities",
    )
