"""Knowledge notes model for Potluck-native notes.

KnowledgeNotes are pieces of useful information stored in Potluck itself,
not imported from external sources like Google Keep or Obsidian.

Think of it as an LLM memory function - capturing insights, facts, and
relationships that don't have a hard tie to a source but can benefit
other models (e.g., "I went to school with Jack", "Alice's favorite
restaurant is Pizzeria Uno").

Notes can be:
- Added directly by users
- Created by LLMs during conversations
- Generated by automated analysis of imported data
"""

from pgvector.sqlalchemy import Vector
from sqlalchemy import Column
from sqlmodel import Field

from potluck.models.base import SimpleEntity


class KnowledgeNote(SimpleEntity, table=True):
    """A Potluck-native knowledge note with text and embedding.

    Used for storing insights, facts, and relationships that enrich
    the knowledge graph without being tied to a specific import source.

    Inherits id, created_at, updated_at from SimpleEntity.
    """

    __tablename__ = "knowledge_notes"

    # Note content
    content: str = Field(
        description="The note text content",
    )
    content_hash: str | None = Field(
        default=None,
        index=True,
        description="SHA256 hash of content for deduplication",
    )

    # Embedding for semantic search
    embedding: list[float] | None = Field(
        default=None,
        sa_column=Column(Vector(768)),
        description="Text embedding vector for semantic search",
    )

    # Creation context
    created_by: str | None = Field(
        default=None,
        description="What created this note (e.g., 'user', 'claude', 'auto-linker')",
    )

    # Optional linked entities (JSON-encoded UUIDs with entity types)
    linked_entities: str | None = Field(
        default=None,
        description="JSON-encoded list of {entity_type, entity_id} for related entities",
    )
