#!/bin/bash
# Potluck Install Script
# One-liner installation for end-users
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/DoubleGremlin181/potluck/main/scripts/install.sh | bash
#   curl -fsSL https://raw.githubusercontent.com/DoubleGremlin181/potluck/main/scripts/install.sh | bash -s -- --gpu
#
# Options:
#   --gpu    Enable GPU support (requires NVIDIA GPU + nvidia-container-toolkit)

set -e

POTLUCK_DIR="${POTLUCK_DIR:-$HOME/.potluck}"
REPO_URL="https://raw.githubusercontent.com/DoubleGremlin181/potluck/main"
GPU=false

# Parse arguments
for arg in "$@"; do
    case $arg in
        --gpu)
            GPU=true
            ;;
    esac
done

echo "🍲 Installing Potluck..."
echo ""

# Check for required tools
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is required but not installed."
    echo "   Install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo "❌ Docker Compose is required but not installed."
    echo "   Docker Compose is included with Docker Desktop, or install separately."
    exit 1
fi

# Create Potluck directory
echo "📁 Creating Potluck directory at $POTLUCK_DIR..."
mkdir -p "$POTLUCK_DIR"
cd "$POTLUCK_DIR"

# Download required files
echo "📥 Downloading configuration files..."
curl -fsSL "$REPO_URL/docker-compose.prod.yml" -o docker-compose.yml
curl -fsSL "$REPO_URL/scripts/init-db.sql" -o init-db.sql

# Generate secure password
echo "🔐 Generating secure credentials..."
DB_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)

# Create .env file
cat > .env << EOF
# Potluck Configuration
# Generated by install.sh on $(date)

# Database
POSTGRES_USER=potluck
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_DB=potluck
POSTGRES_HOST=db
POSTGRES_PORT=5432
DATABASE_URL=postgresql+asyncpg://potluck:$DB_PASSWORD@db:5432/potluck
SYNC_DATABASE_URL=postgresql://potluck:$DB_PASSWORD@db:5432/potluck

# Redis
REDIS_URL=redis://redis:6379/0

# Web Server
WEB_HOST=0.0.0.0
WEB_PORT=8000

# Logging
LOG_LEVEL=INFO

# GPU Support
GPU=$GPU
EOF

# Pull images
echo "🐳 Pulling Docker images (this may take a few minutes)..."
docker compose pull

# Start services
echo "🚀 Starting Potluck services..."
docker compose up -d

# Wait for database
echo "⏳ Waiting for database to be ready..."
timeout=60
counter=0
until docker compose exec -T db pg_isready -U potluck -d potluck &> /dev/null; do
    counter=$((counter + 1))
    if [ $counter -ge $timeout ]; then
        echo "❌ Database did not become ready in time"
        docker compose logs db
        exit 1
    fi
    sleep 1
done

# Wait for encryption setup
echo "⏳ Waiting for encryption setup..."
sleep 5  # Give pg_tde time to initialize

# Run migrations
echo "🔄 Running database migrations..."
docker compose exec -T app uv run alembic upgrade head

echo ""
echo "✅ Potluck is ready!"
echo ""
echo "📊 Web UI: http://localhost:8000"
echo "📁 Data directory: $POTLUCK_DIR"
echo ""
echo "🔧 Useful commands:"
echo "   cd $POTLUCK_DIR && docker compose logs -f    # View logs"
echo "   cd $POTLUCK_DIR && docker compose down       # Stop Potluck"
echo "   cd $POTLUCK_DIR && docker compose up -d      # Start Potluck"
echo ""
echo "🤖 Add to Claude Desktop (claude_desktop_config.json):"
echo ""
cat << 'MCPCONFIG'
{
  "mcpServers": {
    "potluck": {
      "command": "docker",
      "args": ["exec", "-i", "potluck-app", "potluck", "mcp"]
    }
  }
}
MCPCONFIG
echo ""
echo "⚠️  NOTE: Using file-based encryption keys (development mode)"
echo "   For production, configure HashiCorp Vault. See documentation."
echo ""
